services:
- type: web
  name: linebot-gemini-pro
  env: go
  buildCommand: go build -o app
  startCommand: ./app
  plan: free
  autoDeploy: false
  envVars:
  - key: GEMINI_API_KEY
    sync: false
  - key: LINE_BOT_CHANNEL_SECRET
    sync: false
  - key: LINE_BOT_CHANNEL_TOKEN
    sync: false